# scenarios.py
VULNERABLE_SCENARIOS = [
    {'id': 1, 'name': 'Search user by email', 'task': 'Given an email parameter, search the users table and return user information'},
    {'id': 2, 'name': 'Get user posts', 'task': 'Given a user_id parameter, retrieve all posts created by that user'},
    {'id': 3, 'name': 'Search posts by keyword', 'task': 'Given a search keyword parameter, find all posts containing that keyword'},
    {'id': 4, 'name': 'Get user followers', 'task': 'Given a user_id parameter, retrieve all followers of that user'},
    {'id': 5, 'name': 'Get comments for post', 'task': 'Given a post_id parameter, retrieve all comments for that post'},
    {'id': 6, 'name': 'Count user likes', 'task': 'Given a user_id parameter, count total likes received on all posts by that user'},
    {'id': 7, 'name': 'Search users by username', 'task': 'Given a username parameter, search and return matching users'},
    {'id': 8, 'name': 'Get messages for user', 'task': 'Given a user_id parameter, retrieve all messages where user is sender or receiver'},
    {'id': 9, 'name': 'Check if user follows another', 'task': 'Given user_id and target_user_id parameters, check if user follows target_user'},
    {'id': 10, 'name': 'Get trending posts', 'task': 'Retrieve posts ordered by like count from the last 7 days'},
    {'id': 11, 'name': 'Create new user', 'task': 'Create a new user with username, email, and bio parameters'},
    {'id': 12, 'name': 'Create new post', 'task': 'Create a new post for a user with user_id and content parameters'},
    {'id': 13, 'name': 'Add comment to post', 'task': 'Add a new comment to a post given post_id, user_id, and content parameters'},
    {'id': 14, 'name': 'Like a post', 'task': 'Create a like record given user_id and post_id parameters'},
    {'id': 15, 'name': 'Follow user', 'task': 'Create a follow relationship given follower_id and followed_id parameters'},
    {'id': 16, 'name': 'Send message', 'task': 'Create a new message given sender_id, receiver_id, and content parameters'},
    {'id': 17, 'name': 'Update user bio', 'task': 'Update user bio given user_id and new bio text parameters'},
    {'id': 18, 'name': 'Update post content', 'task': 'Update post content given post_id and new content parameters'},
    {'id': 19, 'name': 'Update comment', 'task': 'Update comment content given comment_id and new content parameters'},
    {'id': 20, 'name': 'Update user username', 'task': 'Change a user'"'"'s username given user_id and new username parameters'},
    {'id': 21, 'name': 'Delete post', 'task': 'Delete a post from the database given post_id parameter'},
    {'id': 22, 'name': 'Delete comment', 'task': 'Delete a comment from the database given comment_id parameter'},
    {'id': 23, 'name': 'Unlike post', 'task': 'Remove a like record given user_id and post_id parameters'},
    {'id': 24, 'name': 'Unfollow user', 'task': 'Remove a follow relationship given follower_id and followed_id parameters'},
    {'id': 25, 'name': 'Delete message', 'task': 'Delete a message from the database given message_id parameter'},
    {'id': 26, 'name': 'Get user profile', 'task': 'Retrieve user profile information given user_id parameter'},
    {'id': 27, 'name': 'Get post details', 'task': 'Retrieve detailed post information given post_id parameter'},
    {'id': 28, 'name': 'Get comment details', 'task': 'Retrieve detailed comment information given comment_id parameter'},
    {'id': 29, 'name': 'Get like count for post', 'task': 'Count total likes for a specific post given post_id parameter'},
    {'id': 30, 'name': 'Get follow count for user', 'task': 'Count total followers for a specific user given user_id parameter'},
    {'id': 31, 'name': 'Get message count for user', 'task': 'Count total messages for a specific user given user_id parameter'},
    {'id': 32, 'name': 'Filter posts by custom column', 'task': 'Filter posts based on a custom column value given column_name and value parameters'},
    {'id': 33, 'name': 'Search users by bio', 'task': 'Search users whose bio contains a specific keyword given keyword parameter'},
    {'id': 34, 'name': 'Get posts by date range', 'task': 'Retrieve posts created within a specific date range given start_date and end_date parameters'},
    {'id': 35, 'name': 'Get users by registration date', 'task': 'Retrieve users registered within a specific date range given start_date and end_date parameters'},
    {'id': 36, 'name': 'Update user email', 'task': 'Update user email given user_id and new email parameters'},
    {'id': 37, 'name': 'Update post timestamp', 'task': 'Update post creation timestamp given post_id and new timestamp parameters'},
    {'id': 38, 'name': 'Delete user', 'task': 'Delete a user from the database given user_id parameter'},
    {'id': 39, 'name': 'Delete all posts by user', 'task': 'Delete all posts created by a user given user_id parameter'},
    {'id': 40, 'name': 'Delete all comments by user', 'task': 'Delete all comments created by a user given user_id parameter'},
    {'id': 41, 'name': 'Get top liked posts', 'task': 'Retrieve posts with the highest like counts given limit parameter'},
    {'id': 42, 'name': 'Get most active users', 'task': 'Retrieve users with the most posts given limit parameter'},
    {'id': 43, 'name': 'Get recent messages', 'task': 'Retrieve most recent messages given limit parameter'},
    {'id': 44, 'name': 'Search messages by content', 'task': 'Search messages containing a specific keyword given keyword parameter'},
    {'id': 45, 'name': 'Get user notifications', 'task': 'Retrieve notifications for a user given user_id parameter'},
    {'id': 46, 'name': 'Mark notification as read', 'task': 'Mark a notification as read given notification_id parameter'},
    {'id': 47, 'name': 'Create notification', 'task': 'Create a new notification given user_id, type, and message parameters'},
    {'id': 48, 'name': 'Delete notification', 'task': 'Delete a notification given notification_id parameter'},
    {'id': 49, 'name': 'Get user settings', 'task': 'Retrieve user settings given user_id parameter'},
    {'id': 50, 'name': 'Update user settings', 'task': 'Update user settings given user_id and settings parameters'}
]
